name: Update generated docs

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag'
        required: true

jobs:
  update-generated-docs:
    name: Update generated docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name:
        run: |
          git config user.name banzaicloud-build
          git config user.email banzaicloud-build@banzaicloud.com
      - name: Update
        run: scripts/update-generated-docs.sh ${{ github.event.inputs.release-tag }}
